const { GoogleGenerativeAI } = require('@google/generative-ai');

/**
 * Generate a README.md based on the analysis data
 */
async function generateReadme(analysisJson, apiKey) {
  try {
    const genAI = new GoogleGenerativeAI(apiKey);
    const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash' });

    const systemPrompt = `You are an expert developer who writes excellent, clear, and comprehensive README.md files for software projects.

You will be provided with the JSON analysis of a repository. Your task is to generate a professional README.md that includes:
1. Title and Project description (using the summary data)
2. Features/Tech Stack (using the detected APIs and frameworks)
3. Getting Started / Installation (using the setup steps and env vars)
4. Project Structure / Architecture (using the entry point and file roles)
5. API Reference (summarize the key routes if any)

Make it look beautiful with markdown, badges (if applicable), and clear headings.
Do NOT include a greeting or conversation, just output the raw markdown content for the README.`;

    const result = await model.generateContent([
      systemPrompt,
      { text: `Repository Analysis Data:\n${JSON.stringify(analysisJson, null, 2)}` }
    ]);

    let readmeContent = result.response.text();
    // Clean up any markdown code block fences if the AI wrapped the whole response
    readmeContent = readmeContent.replace(/^```markdown\n/, '').replace(/\n```$/, '');

    return readmeContent;
  } catch (error) {
    console.error('Gemini API Error:', error.message);
    throw new Error('Failed to generate README: ' + error.message);
  }
}

/**
 * Fallback when no API key is provided
 */
function generateFallbackReadme(analysisJson) {
  const { summary, entryPoint, setupSteps, envVars, routes, apis } = analysisJson;
  const { owner, repo } = analysisJson.meta || { owner: 'Owner', repo: 'Repo' };

  let readme = `# ${repo}\n\n`;
  readme += `> ${summary.oneLiner}\n\n`;

  readme += `## 🚀 Getting Started\n\n### Prerequisites\n\nMake sure you have the required dependencies installed.\n\n### Installation\n\n`;
  setupSteps.forEach(step => {
    readme += `**${step.title}**\n\`\`\`bash\n${step.command}\n\`\`\`\n\n`;
  });

  if (envVars.length > 0) {
    readme += `## ⚙️ Environment Variables\n\nCreate a \`.env\` file in the root directory and add the following:\n\n| Variable | Required | Default |\n|---|---|---|\n`;
    envVars.forEach(ev => {
      readme += `| \`${ev.name}\` | ${ev.required ? '✅' : '❌'} | ${ev.defaultValue || '-'} |\n`;
    });
    readme += '\n';
  }

  if (routes.length > 0) {
    readme += `## 🛣️ API Routes\n\n| Method | Path | File |\n|---|---|---|\n`;
    routes.slice(0, 15).forEach(rt => {
      readme += `| \`${rt.method}\` | \`${rt.path}\` | \`${rt.file}\` |\n`;
    });
    if (routes.length > 15) {
      readme += `\n*...and ${routes.length - 15} more routes.*\n`;
    }
    readme += '\n';
  }

  readme += `## 🛠️ Tech Stack\n\n`;
  const categories = {};
  apis.forEach(api => {
    if (!categories[api.category]) categories[api.category] = [];
    categories[api.category].push(api.name);
  });
  
  for (const [cat, items] of Object.entries(categories)) {
    readme += `- **${cat.charAt(0).toUpperCase() + cat.slice(1)}**: ${items.join(', ')}\n`;
  }

  readme += `\n---\n*Auto-generated by RepoPilot*`;
  return readme;
}

module.exports = {
  generateReadme,
  generateFallbackReadme
};
